defmodule ExStreamClient.Model.AppResponseFields do
  @moduledoc "Schema representing a AppResponseFields"
  use ExStreamClient.Jason

  @enforce_keys [
    :policies,
    :sns_secret,
    :call_types,
    :organization,
    :image_upload_config,
    :campaign_enabled,
    :moderation_webhook_url,
    :async_url_enrich_enabled,
    :cdn_expiration_seconds,
    :grants,
    :disable_auth_checks,
    :suspended,
    :guest_user_creation_disabled,
    :custom_action_handler_url,
    :moderation_enabled,
    :sns_topic_arn,
    :reminders_interval,
    :sqs_key,
    :channel_configs,
    :multi_tenant_enabled,
    :name,
    :enforce_unique_usernames,
    :push_notifications,
    :moderation_multitenant_blocklist_enabled,
    :user_search_disallowed_roles,
    :sqs_secret,
    :auto_translation_enabled,
    :suspended_explanation,
    :sqs_url,
    :webhook_events,
    :permission_version,
    :webhook_url,
    :disable_permissions_checks,
    :file_upload_config,
    :sns_key,
    :image_moderation_enabled
  ]
  defstruct [
    :permission_version,
    :suspended_explanation,
    :disable_permissions_checks,
    :disable_auth_checks,
    :image_moderation_enabled,
    :custom_action_handler_url,
    :moderation_webhook_url,
    :moderation_multitenant_blocklist_enabled,
    :auto_translation_enabled,
    :async_url_enrich_enabled,
    :enforce_unique_usernames,
    :campaign_enabled,
    :reminders_interval,
    :organization,
    :moderation_dashboard_preferences,
    :before_message_send_hook_url,
    :guest_user_creation_disabled,
    :datadog_info,
    :user_search_disallowed_roles,
    :sns_secret,
    :grants,
    :allowed_flag_reasons,
    :sqs_secret,
    :sqs_key,
    :policies,
    :sns_topic_arn,
    :multi_tenant_enabled,
    :webhook_events,
    :file_upload_config,
    :sns_key,
    :image_moderation_labels,
    :cdn_expiration_seconds,
    :image_upload_config,
    :suspended,
    :revoke_tokens_issued_before,
    :sqs_url,
    :name,
    :geofences,
    :call_types,
    :channel_configs,
    :push_notifications,
    :moderation_enabled,
    :webhook_url
  ]

  @type t :: %__MODULE__{
          permission_version: String.t(),
          suspended_explanation: String.t(),
          disable_permissions_checks: boolean(),
          disable_auth_checks: boolean(),
          image_moderation_enabled: boolean(),
          custom_action_handler_url: String.t(),
          moderation_webhook_url: String.t(),
          moderation_multitenant_blocklist_enabled: boolean(),
          auto_translation_enabled: boolean(),
          async_url_enrich_enabled: boolean(),
          enforce_unique_usernames: String.t(),
          campaign_enabled: boolean(),
          reminders_interval: integer(),
          organization: String.t(),
          moderation_dashboard_preferences:
            ExStreamClient.Model.ModerationDashboardPreferences.t() | nil,
          before_message_send_hook_url: String.t() | nil,
          guest_user_creation_disabled: boolean(),
          datadog_info: ExStreamClient.Model.DataDogInfo.t() | nil,
          user_search_disallowed_roles: [String.t()],
          sns_secret: String.t(),
          grants: map(),
          allowed_flag_reasons: [String.t()] | nil,
          sqs_secret: String.t(),
          sqs_key: String.t(),
          policies: map(),
          sns_topic_arn: String.t(),
          multi_tenant_enabled: boolean(),
          webhook_events: [String.t()],
          file_upload_config: ExStreamClient.Model.FileUploadConfig.t(),
          sns_key: String.t(),
          image_moderation_labels: [String.t()] | nil,
          cdn_expiration_seconds: integer(),
          image_upload_config: ExStreamClient.Model.FileUploadConfig.t(),
          suspended: boolean(),
          revoke_tokens_issued_before: float() | nil,
          sqs_url: String.t(),
          name: String.t(),
          geofences: [ExStreamClient.Model.GeofenceResponse.t()] | nil,
          call_types: map(),
          channel_configs: map(),
          push_notifications: ExStreamClient.Model.PushNotificationFields.t(),
          moderation_enabled: boolean(),
          webhook_url: String.t()
        }
end