defmodule ExStreamClient.Model.ChannelConfigWithInfo do
  @moduledoc "Schema representing a ChannelConfigWithInfo"
  use ExStreamClient.Jason

  @enforce_keys [
    :automod,
    :automod_behavior,
    :commands,
    :connect_events,
    :created_at,
    :custom_events,
    :mark_messages_pending,
    :max_message_length,
    :mutes,
    :name,
    :polls,
    :push_notifications,
    :quotes,
    :reactions,
    :read_events,
    :reminders,
    :replies,
    :search,
    :skip_last_msg_update_for_system_msgs,
    :typing_events,
    :updated_at,
    :uploads,
    :url_enrichment
  ]
  defstruct [
    :name,
    :search,
    :replies,
    :commands,
    :created_at,
    :reactions,
    :updated_at,
    :automod,
    :automod_behavior,
    :max_message_length,
    :allowed_flag_reasons,
    :automod_thresholds,
    :blocklist,
    :blocklist_behavior,
    :blocklists,
    :connect_events,
    :custom_events,
    :grants,
    :mark_messages_pending,
    :mutes,
    :partition_size,
    :partition_ttl,
    :polls,
    :push_notifications,
    :quotes,
    :read_events,
    :reminders,
    :skip_last_msg_update_for_system_msgs,
    :typing_events,
    :uploads,
    :url_enrichment
  ]

  @type t :: %__MODULE__{
          name: String.t(),
          search: boolean(),
          replies: boolean(),
          commands: [ExStreamClient.Model.Command.t()],
          created_at: float(),
          reactions: boolean(),
          updated_at: float(),
          automod: :AI | :simple | :disabled,
          automod_behavior: :shadow_block | :block | :flag,
          max_message_length: integer(),
          allowed_flag_reasons: [String.t()] | nil,
          automod_thresholds: ExStreamClient.Model.Thresholds.t() | nil,
          blocklist: String.t() | nil,
          blocklist_behavior: (:shadow_block | :block | :flag) | nil,
          blocklists: [ExStreamClient.Model.BlockListOptions.t()] | nil,
          connect_events: boolean(),
          custom_events: boolean(),
          grants: map() | nil,
          mark_messages_pending: boolean(),
          mutes: boolean(),
          partition_size: integer() | nil,
          partition_ttl: String.t() | nil,
          polls: boolean(),
          push_notifications: boolean(),
          quotes: boolean(),
          read_events: boolean(),
          reminders: boolean(),
          skip_last_msg_update_for_system_msgs: boolean(),
          typing_events: boolean(),
          uploads: boolean(),
          url_enrichment: boolean()
        }
end