defmodule ExStreamClient.Model.FullUserResponse do
  @moduledoc "Schema representing a FullUserResponse"
  use ExStreamClient.Jason

  @enforce_keys [
    :banned,
    :blocked_user_ids,
    :channel_mutes,
    :created_at,
    :custom,
    :devices,
    :id,
    :invisible,
    :language,
    :mutes,
    :online,
    :role,
    :shadow_banned,
    :teams,
    :total_unread_count,
    :unread_channels,
    :unread_count,
    :unread_threads,
    :updated_at
  ]
  defstruct [
    :id,
    :name,
    :image,
    :role,
    :language,
    :custom,
    :created_at,
    :updated_at,
    :mutes,
    :banned,
    :channel_mutes,
    :devices,
    :online,
    :total_unread_count,
    :unread_channels,
    :unread_count,
    :unread_threads,
    :blocked_user_ids,
    :deactivated_at,
    :deleted_at,
    :invisible,
    :last_active,
    :latest_hidden_channels,
    :privacy_settings,
    :teams,
    :teams_role,
    :ban_expires,
    :revoke_tokens_issued_before,
    :shadow_banned
  ]

  @type t :: %__MODULE__{
          id: String.t(),
          name: String.t() | nil,
          image: String.t() | nil,
          role: String.t(),
          language: String.t(),
          custom: map(),
          created_at: float(),
          updated_at: float(),
          mutes: [ExStreamClient.Model.UserMuteResponse.t()],
          banned: boolean(),
          channel_mutes: [ExStreamClient.Model.ChannelMute.t()],
          devices: [ExStreamClient.Model.DeviceResponse.t()],
          online: boolean(),
          total_unread_count: integer(),
          unread_channels: integer(),
          unread_count: integer(),
          unread_threads: integer(),
          blocked_user_ids: [String.t()],
          deactivated_at: float() | nil,
          deleted_at: float() | nil,
          invisible: boolean(),
          last_active: float() | nil,
          latest_hidden_channels: [String.t()] | nil,
          privacy_settings: ExStreamClient.Model.PrivacySettingsResponse.t() | nil,
          teams: [String.t()],
          teams_role: map() | nil,
          ban_expires: float() | nil,
          revoke_tokens_issued_before: float() | nil,
          shadow_banned: boolean()
        }
end