defmodule ExStreamClient.Model.MessageWithChannelResponse do
  @moduledoc "Schema representing a MessageWithChannelResponse"
  use ExStreamClient.Jason

  @enforce_keys [
    :created_at,
    :silent,
    :deleted_reply_count,
    :reply_count,
    :reaction_counts,
    :html,
    :restricted_visibility,
    :pinned,
    :own_reactions,
    :user,
    :id,
    :channel,
    :updated_at,
    :custom,
    :latest_reactions,
    :cid,
    :type,
    :attachments,
    :mentioned_users,
    :text,
    :reaction_scores,
    :shadowed
  ]
  defstruct [
    :poll,
    :reaction_groups,
    :user,
    :pin_expires,
    :restricted_visibility,
    :draft,
    :poll_id,
    :message_text_updated_at,
    :reaction_scores,
    :thread_participants,
    :silent,
    :deleted_reply_count,
    :reply_count,
    :deleted_at,
    :created_at,
    :image_labels,
    :pinned_at,
    :pinned_by,
    :attachments,
    :pinned,
    :cid,
    :custom,
    :moderation,
    :reaction_counts,
    :shadowed,
    :command,
    :mentioned_users,
    :own_reactions,
    :html,
    :show_in_channel,
    :latest_reactions,
    :parent_id,
    :quoted_message_id,
    :quoted_message,
    :channel,
    :mml,
    :id,
    :updated_at,
    :text,
    :i18n,
    :type
  ]

  @type t :: %__MODULE__{
          poll: ExStreamClient.Model.PollResponseData.t() | nil,
          reaction_groups: map() | nil,
          user: ExStreamClient.Model.UserResponse.t(),
          pin_expires: float() | nil,
          restricted_visibility: [String.t()],
          draft: ExStreamClient.Model.DraftResponse.t() | nil,
          poll_id: String.t() | nil,
          message_text_updated_at: float() | nil,
          reaction_scores: map(),
          thread_participants: [ExStreamClient.Model.UserResponse.t()] | nil,
          silent: boolean(),
          deleted_reply_count: integer(),
          reply_count: integer(),
          deleted_at: float() | nil,
          created_at: float(),
          image_labels: map() | nil,
          pinned_at: float() | nil,
          pinned_by: ExStreamClient.Model.UserResponse.t() | nil,
          attachments: [ExStreamClient.Model.Attachment.t()],
          pinned: boolean(),
          cid: String.t(),
          custom: map(),
          moderation: ExStreamClient.Model.ModerationV2Response.t() | nil,
          reaction_counts: map(),
          shadowed: boolean(),
          command: String.t() | nil,
          mentioned_users: [ExStreamClient.Model.UserResponse.t()],
          own_reactions: [ExStreamClient.Model.ReactionResponse.t()],
          html: String.t(),
          show_in_channel: boolean() | nil,
          latest_reactions: [ExStreamClient.Model.ReactionResponse.t()],
          parent_id: String.t() | nil,
          quoted_message_id: String.t() | nil,
          quoted_message: ExStreamClient.Model.MessageResponse.t() | nil,
          channel: ExStreamClient.Model.ChannelResponse.t(),
          mml: String.t() | nil,
          id: String.t(),
          updated_at: float(),
          text: String.t(),
          i18n: map() | nil,
          type: :deleted | :system | :reply | :error | :ephemeral | :regular
        }
end