defmodule ExStreamClient.Model.ReviewQueueItemResponse do
  @moduledoc "Schema representing a ReviewQueueItemResponse"
  use ExStreamClient.Jason

  @enforce_keys [
    :actions,
    :ai_text_severity,
    :bans,
    :created_at,
    :entity_id,
    :entity_type,
    :flags,
    :flags_count,
    :id,
    :languages,
    :recommended_action,
    :reviewed_by,
    :severity,
    :status,
    :updated_at
  ]
  defstruct [
    :call,
    :flags,
    :id,
    :message,
    :status,
    :severity,
    :created_at,
    :updated_at,
    :teams,
    :actions,
    :reviewed_at,
    :reviewed_by,
    :entity_id,
    :entity_type,
    :entity_creator_id,
    :moderation_payload,
    :reaction,
    :recommended_action,
    :ai_text_severity,
    :bans,
    :flags_count,
    :languages,
    :activity,
    :assigned_to,
    :completed_at,
    :config_key,
    :entity_creator,
    :feeds_v2_activity,
    :feeds_v2_reaction
  ]

  @type t :: %__MODULE__{
          call: ExStreamClient.Model.CallResponse.t() | nil,
          flags: [ExStreamClient.Model.FlagResponse.t()],
          id: String.t(),
          message: ExStreamClient.Model.MessageResponse.t() | nil,
          status: String.t(),
          severity: integer(),
          created_at: float(),
          updated_at: float(),
          teams: [String.t()] | nil,
          actions: [ExStreamClient.Model.ActionLogResponse.t()],
          reviewed_at: float() | nil,
          reviewed_by: String.t(),
          entity_id: String.t(),
          entity_type: String.t(),
          entity_creator_id: String.t() | nil,
          moderation_payload: ExStreamClient.Model.ModerationPayload.t() | nil,
          reaction: ExStreamClient.Model.Reaction.t() | nil,
          recommended_action: String.t(),
          ai_text_severity: String.t(),
          bans: [ExStreamClient.Model.Ban.t()],
          flags_count: integer(),
          languages: [String.t()],
          activity: ExStreamClient.Model.EnrichedActivity.t() | nil,
          assigned_to: ExStreamClient.Model.UserResponse.t() | nil,
          completed_at: float() | nil,
          config_key: String.t() | nil,
          entity_creator: ExStreamClient.Model.EntityCreatorResponse.t() | nil,
          feeds_v2_activity: ExStreamClient.Model.EnrichedActivity.t() | nil,
          feeds_v2_reaction: ExStreamClient.Model.Reaction.t() | nil
        }
end