defmodule ExStreamClient.Model.UpdateAppRequest do
  @moduledoc "Schema representing a UpdateAppRequest"
  use ExStreamClient.Jason

  defstruct [
    :permission_version,
    :migrate_permissions_to_v2,
    :disable_permissions_checks,
    :disable_auth_checks,
    :firebase_config,
    :image_moderation_enabled,
    :push_config,
    :custom_action_handler_url,
    :moderation_webhook_url,
    :reminders_max_members,
    :feeds_moderation_enabled,
    :channel_hide_members_only,
    :auto_translation_enabled,
    :image_moderation_block_labels,
    :async_url_enrich_enabled,
    :enforce_unique_usernames,
    :async_moderation_config,
    :reminders_interval,
    :moderation_dashboard_preferences,
    :before_message_send_hook_url,
    :guest_user_creation_disabled,
    :datadog_info,
    :xiaomi_config,
    :user_search_disallowed_roles,
    :huawei_config,
    :sns_secret,
    :grants,
    :allowed_flag_reasons,
    :sqs_secret,
    :sqs_key,
    :sns_topic_arn,
    :multi_tenant_enabled,
    :webhook_events,
    :file_upload_config,
    :sns_key,
    :image_moderation_labels,
    :cdn_expiration_seconds,
    :image_upload_config,
    :revoke_tokens_issued_before,
    :sqs_url,
    :apn_config,
    :moderation_enabled,
    :webhook_url,
    :feeds_v2_region
  ]

  @type t :: %__MODULE__{
          permission_version: (:v2 | :v1) | nil,
          migrate_permissions_to_v2: boolean() | nil,
          disable_permissions_checks: boolean() | nil,
          disable_auth_checks: boolean() | nil,
          firebase_config: ExStreamClient.Model.FirebaseConfig.t() | nil,
          image_moderation_enabled: boolean() | nil,
          push_config: ExStreamClient.Model.PushConfig.t() | nil,
          custom_action_handler_url: String.t() | nil,
          moderation_webhook_url: String.t() | nil,
          reminders_max_members: integer() | nil,
          feeds_moderation_enabled: boolean() | nil,
          channel_hide_members_only: boolean() | nil,
          auto_translation_enabled: boolean() | nil,
          image_moderation_block_labels: [String.t()] | nil,
          async_url_enrich_enabled: boolean() | nil,
          enforce_unique_usernames: (:team | :app | :no) | nil,
          async_moderation_config: ExStreamClient.Model.AsyncModerationConfiguration.t() | nil,
          reminders_interval: integer() | nil,
          moderation_dashboard_preferences:
            ExStreamClient.Model.ModerationDashboardPreferences.t() | nil,
          before_message_send_hook_url: String.t() | nil,
          guest_user_creation_disabled: boolean() | nil,
          datadog_info: ExStreamClient.Model.DataDogInfo.t() | nil,
          xiaomi_config: ExStreamClient.Model.XiaomiConfig.t() | nil,
          user_search_disallowed_roles: [String.t()] | nil,
          huawei_config: ExStreamClient.Model.HuaweiConfig.t() | nil,
          sns_secret: String.t() | nil,
          grants: map() | nil,
          allowed_flag_reasons: [String.t()] | nil,
          sqs_secret: String.t() | nil,
          sqs_key: String.t() | nil,
          sns_topic_arn: String.t() | nil,
          multi_tenant_enabled: boolean() | nil,
          webhook_events: [String.t()] | nil,
          file_upload_config: ExStreamClient.Model.FileUploadConfig.t() | nil,
          sns_key: String.t() | nil,
          image_moderation_labels: [String.t()] | nil,
          cdn_expiration_seconds: integer() | nil,
          image_upload_config: ExStreamClient.Model.FileUploadConfig.t() | nil,
          revoke_tokens_issued_before: float() | nil,
          sqs_url: String.t() | nil,
          apn_config: ExStreamClient.Model.APNConfig.t() | nil,
          moderation_enabled: boolean() | nil,
          webhook_url: String.t() | nil,
          feeds_v2_region: String.t() | nil
        }
end