defmodule ExStreamClient.Model.AppResponseFields do
  @moduledoc "Schema representing a AppResponseFields"
  use ExStreamClient.JSON
  use ExStreamClient.TypeInterner

  @enforce_keys [
    :async_url_enrich_enabled,
    :auto_translation_enabled,
    :call_types,
    :campaign_enabled,
    :cdn_expiration_seconds,
    :channel_configs,
    :custom_action_handler_url,
    :disable_auth_checks,
    :disable_permissions_checks,
    :enforce_unique_usernames,
    :event_hooks,
    :file_upload_config,
    :grants,
    :guest_user_creation_disabled,
    :image_moderation_enabled,
    :image_upload_config,
    :moderation_enabled,
    :moderation_multitenant_blocklist_enabled,
    :moderation_webhook_url,
    :multi_tenant_enabled,
    :name,
    :organization,
    :permission_version,
    :policies,
    :push_notifications,
    :reminders_interval,
    :sns_key,
    :sns_secret,
    :sns_topic_arn,
    :sqs_key,
    :sqs_secret,
    :sqs_url,
    :suspended,
    :suspended_explanation,
    :use_hook_v2,
    :user_search_disallowed_roles,
    :video_provider,
    :webhook_events,
    :webhook_url
  ]
  defstruct [
    :allowed_flag_reasons,
    :async_url_enrich_enabled,
    :auto_translation_enabled,
    :before_message_send_hook_url,
    :call_types,
    :campaign_enabled,
    :cdn_expiration_seconds,
    :channel_configs,
    :custom_action_handler_url,
    :datadog_info,
    :disable_auth_checks,
    :disable_permissions_checks,
    :enforce_unique_usernames,
    :event_hooks,
    :file_upload_config,
    :geofences,
    :grants,
    :guest_user_creation_disabled,
    :image_moderation_enabled,
    :image_moderation_labels,
    :image_upload_config,
    :moderation_dashboard_preferences,
    :moderation_enabled,
    :moderation_multitenant_blocklist_enabled,
    :moderation_webhook_url,
    :multi_tenant_enabled,
    :name,
    :organization,
    :permission_version,
    :policies,
    :push_notifications,
    :reminders_interval,
    :revoke_tokens_issued_before,
    :sns_key,
    :sns_secret,
    :sns_topic_arn,
    :sqs_key,
    :sqs_secret,
    :sqs_url,
    :suspended,
    :suspended_explanation,
    :use_hook_v2,
    :user_search_disallowed_roles,
    :video_provider,
    :webhook_events,
    :webhook_url
  ]

  @nested_components call_types: {:map, ExStreamClient.Model.CallType},
                     channel_configs: {:map, ExStreamClient.Model.ChannelConfig},
                     datadog_info: ExStreamClient.Model.DataDogInfo,
                     event_hooks: ExStreamClient.Model.EventHook,
                     file_upload_config: ExStreamClient.Model.FileUploadConfig,
                     geofences: ExStreamClient.Model.GeofenceResponse,
                     image_upload_config: ExStreamClient.Model.FileUploadConfig,
                     moderation_dashboard_preferences:
                       ExStreamClient.Model.ModerationDashboardPreferences,
                     policies: {:map, {:array, ExStreamClient.Model.Policy}},
                     push_notifications: ExStreamClient.Model.PushNotificationFields
  def nested_components do
    @nested_components
  end

  @type t :: %__MODULE__{
          allowed_flag_reasons: [String.t()] | nil,
          async_url_enrich_enabled: boolean(),
          auto_translation_enabled: boolean(),
          before_message_send_hook_url: String.t() | nil,
          call_types: %{optional(String.t()) => ExStreamClient.Model.CallType.t()},
          campaign_enabled: boolean(),
          cdn_expiration_seconds: integer(),
          channel_configs: %{optional(String.t()) => ExStreamClient.Model.ChannelConfig.t()},
          custom_action_handler_url: String.t(),
          datadog_info: ExStreamClient.Model.DataDogInfo.t() | nil,
          disable_auth_checks: boolean(),
          disable_permissions_checks: boolean(),
          enforce_unique_usernames: String.t(),
          event_hooks: [ExStreamClient.Model.EventHook.t()],
          file_upload_config: ExStreamClient.Model.FileUploadConfig.t(),
          geofences: [ExStreamClient.Model.GeofenceResponse.t()] | nil,
          grants: %{optional(String.t()) => [String.t()]},
          guest_user_creation_disabled: boolean(),
          image_moderation_enabled: boolean(),
          image_moderation_labels: [String.t()] | nil,
          image_upload_config: ExStreamClient.Model.FileUploadConfig.t(),
          moderation_dashboard_preferences:
            ExStreamClient.Model.ModerationDashboardPreferences.t() | nil,
          moderation_enabled: boolean(),
          moderation_multitenant_blocklist_enabled: boolean(),
          moderation_webhook_url: String.t(),
          multi_tenant_enabled: boolean(),
          name: String.t(),
          organization: String.t(),
          permission_version: String.t(),
          policies: %{optional(String.t()) => [ExStreamClient.Model.Policy.t()]},
          push_notifications: ExStreamClient.Model.PushNotificationFields.t(),
          reminders_interval: integer(),
          revoke_tokens_issued_before: float() | nil,
          sns_key: String.t(),
          sns_secret: String.t(),
          sns_topic_arn: String.t(),
          sqs_key: String.t(),
          sqs_secret: String.t(),
          sqs_url: String.t(),
          suspended: boolean(),
          suspended_explanation: String.t(),
          use_hook_v2: boolean(),
          user_search_disallowed_roles: [String.t()],
          video_provider: any(),
          webhook_events: [String.t()],
          webhook_url: String.t()
        }
end
