defmodule ExStreamClient.Model.Call do
  @moduledoc "Schema representing a Call"
  use ExStreamClient.Jason

  @enforce_keys [
    :app_pk,
    :backstage,
    :blocked_user_i_ds,
    :blocked_users,
    :channel_cid,
    :cid,
    :created_at,
    :created_by_user_id,
    :current_session_id,
    :custom,
    :egresses,
    :id,
    :last_session_id,
    :members,
    :team,
    :thumbnail_url,
    :type,
    :updated_at
  ]
  defstruct [
    :app_pk,
    :backstage,
    :blocked_user_i_ds,
    :blocked_users,
    :call_type,
    :channel_cid,
    :cid,
    :created_at,
    :created_by,
    :created_by_user_id,
    :current_session_id,
    :custom,
    :deleted_at,
    :egress_updated_at,
    :egresses,
    :ended_at,
    :id,
    :join_ahead_time_seconds,
    :last_heartbeat_at,
    :last_session_id,
    :member_count,
    :member_lookup,
    :members,
    :session,
    :settings,
    :settings_overrides,
    :starts_at,
    :team,
    :thumbnail_url,
    :type,
    :updated_at
  ]

  @type t :: %__MODULE__{
          app_pk: integer(),
          backstage: boolean(),
          blocked_user_i_ds: [String.t()],
          blocked_users: [ExStreamClient.Model.User.t()],
          call_type: ExStreamClient.Model.CallType.t() | nil,
          channel_cid: String.t(),
          cid: String.t(),
          created_at: float(),
          created_by: ExStreamClient.Model.User.t() | nil,
          created_by_user_id: String.t(),
          current_session_id: String.t(),
          custom: map(),
          deleted_at: float() | nil,
          egress_updated_at: float() | nil,
          egresses: [ExStreamClient.Model.CallEgress.t()],
          ended_at: float() | nil,
          id: String.t(),
          join_ahead_time_seconds: integer() | nil,
          last_heartbeat_at: float() | nil,
          last_session_id: String.t(),
          member_count: integer() | nil,
          member_lookup: ExStreamClient.Model.MemberLookup.t() | nil,
          members: [ExStreamClient.Model.CallMember.t()],
          session: ExStreamClient.Model.CallSession.t() | nil,
          settings: ExStreamClient.Model.CallSettings.t() | nil,
          settings_overrides: ExStreamClient.Model.CallSettings.t() | nil,
          starts_at: float() | nil,
          team: String.t(),
          thumbnail_url: String.t(),
          type: String.t(),
          updated_at: float()
        }
end