defmodule ExStreamClient.Model.MessageResponse do
  @moduledoc "Schema representing a MessageResponse"
  use ExStreamClient.JSON
  use ExStreamClient.TypeInterner

  @enforce_keys [
    :attachments,
    :cid,
    :created_at,
    :custom,
    :deleted_reply_count,
    :html,
    :id,
    :latest_reactions,
    :mentioned_users,
    :own_reactions,
    :pinned,
    :reaction_counts,
    :reaction_scores,
    :reply_count,
    :restricted_visibility,
    :shadowed,
    :silent,
    :text,
    :type,
    :updated_at,
    :user
  ]
  defstruct [
    :attachments,
    :cid,
    :command,
    :created_at,
    :custom,
    :deleted_at,
    :deleted_reply_count,
    :draft,
    :html,
    :i18n,
    :id,
    :image_labels,
    :latest_reactions,
    :mentioned_users,
    :message_text_updated_at,
    :mml,
    :moderation,
    :own_reactions,
    :parent_id,
    :pin_expires,
    :pinned,
    :pinned_at,
    :pinned_by,
    :poll,
    :poll_id,
    :quoted_message,
    :quoted_message_id,
    :reaction_counts,
    :reaction_groups,
    :reaction_scores,
    :reply_count,
    :restricted_visibility,
    :shadowed,
    :show_in_channel,
    :silent,
    :text,
    :thread_participants,
    :type,
    :updated_at,
    :user
  ]

  @nested_components attachments: ExStreamClient.Model.Attachment,
                     draft: ExStreamClient.Model.DraftResponse,
                     latest_reactions: ExStreamClient.Model.ReactionResponse,
                     mentioned_users: ExStreamClient.Model.UserResponse,
                     moderation: ExStreamClient.Model.ModerationV2Response,
                     own_reactions: ExStreamClient.Model.ReactionResponse,
                     pinned_by: ExStreamClient.Model.UserResponse,
                     poll: ExStreamClient.Model.PollResponseData,
                     quoted_message: ExStreamClient.Model.MessageResponse,
                     reaction_groups: {:map, ExStreamClient.Model.ReactionGroupResponse},
                     thread_participants: ExStreamClient.Model.UserResponse,
                     type: :enum,
                     user: ExStreamClient.Model.UserResponse
  def nested_components do
    @nested_components
  end

  @type t :: %__MODULE__{
          attachments: [ExStreamClient.Model.Attachment.t()],
          cid: String.t(),
          command: String.t() | nil,
          created_at: float(),
          custom: %{optional(String.t()) => any()},
          deleted_at: float() | nil,
          deleted_reply_count: integer(),
          draft: ExStreamClient.Model.DraftResponse.t() | nil,
          html: String.t(),
          i18n: %{optional(String.t()) => String.t()} | nil,
          id: String.t(),
          image_labels: %{optional(String.t()) => [String.t()]} | nil,
          latest_reactions: [ExStreamClient.Model.ReactionResponse.t()],
          mentioned_users: [ExStreamClient.Model.UserResponse.t()],
          message_text_updated_at: float() | nil,
          mml: String.t() | nil,
          moderation: ExStreamClient.Model.ModerationV2Response.t() | nil,
          own_reactions: [ExStreamClient.Model.ReactionResponse.t()],
          parent_id: String.t() | nil,
          pin_expires: float() | nil,
          pinned: boolean(),
          pinned_at: float() | nil,
          pinned_by: ExStreamClient.Model.UserResponse.t() | nil,
          poll: ExStreamClient.Model.PollResponseData.t() | nil,
          poll_id: String.t() | nil,
          quoted_message: ExStreamClient.Model.MessageResponse.t() | nil,
          quoted_message_id: String.t() | nil,
          reaction_counts: %{optional(String.t()) => integer()},
          reaction_groups:
            %{optional(String.t()) => ExStreamClient.Model.ReactionGroupResponse.t()} | nil,
          reaction_scores: %{optional(String.t()) => integer()},
          reply_count: integer(),
          restricted_visibility: [String.t()],
          shadowed: boolean(),
          show_in_channel: boolean() | nil,
          silent: boolean(),
          text: String.t(),
          thread_participants: [ExStreamClient.Model.UserResponse.t()] | nil,
          type: :deleted | :system | :reply | :error | :ephemeral | :regular,
          updated_at: float(),
          user: ExStreamClient.Model.UserResponse.t()
        }
end
