defmodule ExStreamClient.Model.UpdateAppRequest do
  @moduledoc "Schema representing a UpdateAppRequest"
  use ExStreamClient.JSON
  use ExStreamClient.TypeInterner

  defstruct [
    :allowed_flag_reasons,
    :apn_config,
    :async_moderation_config,
    :async_url_enrich_enabled,
    :auto_translation_enabled,
    :before_message_send_hook_url,
    :cdn_expiration_seconds,
    :channel_hide_members_only,
    :custom_action_handler_url,
    :datadog_info,
    :disable_auth_checks,
    :disable_permissions_checks,
    :enforce_unique_usernames,
    :event_hooks,
    :feeds_moderation_enabled,
    :feeds_v2_region,
    :file_upload_config,
    :firebase_config,
    :grants,
    :guest_user_creation_disabled,
    :huawei_config,
    :image_moderation_block_labels,
    :image_moderation_enabled,
    :image_moderation_labels,
    :image_upload_config,
    :migrate_permissions_to_v2,
    :moderation_dashboard_preferences,
    :moderation_enabled,
    :moderation_webhook_url,
    :multi_tenant_enabled,
    :permission_version,
    :push_config,
    :reminders_interval,
    :reminders_max_members,
    :revoke_tokens_issued_before,
    :sns_key,
    :sns_secret,
    :sns_topic_arn,
    :sqs_key,
    :sqs_secret,
    :sqs_url,
    :user_response_time_enabled,
    :user_search_disallowed_roles,
    :webhook_events,
    :webhook_url,
    :xiaomi_config
  ]

  @nested_components apn_config: ExStreamClient.Model.APNConfig,
                     async_moderation_config: ExStreamClient.Model.AsyncModerationConfiguration,
                     datadog_info: ExStreamClient.Model.DataDogInfo,
                     enforce_unique_usernames: :enum,
                     event_hooks: ExStreamClient.Model.EventHook,
                     file_upload_config: ExStreamClient.Model.FileUploadConfig,
                     firebase_config: ExStreamClient.Model.FirebaseConfig,
                     huawei_config: ExStreamClient.Model.HuaweiConfig,
                     image_upload_config: ExStreamClient.Model.FileUploadConfig,
                     moderation_dashboard_preferences:
                       ExStreamClient.Model.ModerationDashboardPreferences,
                     permission_version: :enum,
                     push_config: ExStreamClient.Model.PushConfig,
                     revoke_tokens_issued_before: :datetime,
                     xiaomi_config: ExStreamClient.Model.XiaomiConfig
  def nested_components do
    @nested_components
  end

  @type t :: %__MODULE__{
          allowed_flag_reasons: [String.t()] | nil,
          apn_config: ExStreamClient.Model.APNConfig.t() | nil,
          async_moderation_config: ExStreamClient.Model.AsyncModerationConfiguration.t() | nil,
          async_url_enrich_enabled: boolean() | nil,
          auto_translation_enabled: boolean() | nil,
          before_message_send_hook_url: String.t() | nil,
          cdn_expiration_seconds: integer() | nil,
          channel_hide_members_only: boolean() | nil,
          custom_action_handler_url: String.t() | nil,
          datadog_info: ExStreamClient.Model.DataDogInfo.t() | nil,
          disable_auth_checks: boolean() | nil,
          disable_permissions_checks: boolean() | nil,
          enforce_unique_usernames: (:team | :app | :no) | nil,
          event_hooks: [ExStreamClient.Model.EventHook.t()] | nil,
          feeds_moderation_enabled: boolean() | nil,
          feeds_v2_region: String.t() | nil,
          file_upload_config: ExStreamClient.Model.FileUploadConfig.t() | nil,
          firebase_config: ExStreamClient.Model.FirebaseConfig.t() | nil,
          grants: %{optional(String.t()) => [String.t()]} | nil,
          guest_user_creation_disabled: boolean() | nil,
          huawei_config: ExStreamClient.Model.HuaweiConfig.t() | nil,
          image_moderation_block_labels: [String.t()] | nil,
          image_moderation_enabled: boolean() | nil,
          image_moderation_labels: [String.t()] | nil,
          image_upload_config: ExStreamClient.Model.FileUploadConfig.t() | nil,
          migrate_permissions_to_v2: boolean() | nil,
          moderation_dashboard_preferences:
            ExStreamClient.Model.ModerationDashboardPreferences.t() | nil,
          moderation_enabled: boolean() | nil,
          moderation_webhook_url: String.t() | nil,
          multi_tenant_enabled: boolean() | nil,
          permission_version: (:v2 | :v1) | nil,
          push_config: ExStreamClient.Model.PushConfig.t() | nil,
          reminders_interval: integer() | nil,
          reminders_max_members: integer() | nil,
          revoke_tokens_issued_before: (DateTime.t() | integer() | String.t()) | nil,
          sns_key: String.t() | nil,
          sns_secret: String.t() | nil,
          sns_topic_arn: String.t() | nil,
          sqs_key: String.t() | nil,
          sqs_secret: String.t() | nil,
          sqs_url: String.t() | nil,
          user_response_time_enabled: boolean() | nil,
          user_search_disallowed_roles: [String.t()] | nil,
          webhook_events: [String.t()] | nil,
          webhook_url: String.t() | nil,
          xiaomi_config: ExStreamClient.Model.XiaomiConfig.t() | nil
        }
end
